/**
 * @fileoverview Builder for the 'Read Me & Guide' sheet tab.
 * Creates a clean, elegant metric dictionary focused purely on
 * how to read and understand all KPI cards, ratios, and table columns.
 */

/**
 * Creates or refreshes the 'Read Me & Guide' tab.
 * @param {GoogleAppsScript.Spreadsheet.Spreadsheet} [targetSpreadsheet]
 * @returns {GoogleAppsScript.Spreadsheet.Sheet}
 */
function buildReadMeSheet(targetSpreadsheet) {
  const ss = targetSpreadsheet || SpreadsheetApp.getActiveSpreadsheet();
  const tabName = '📖 Read Me & Guide';

  let sheet = ss.getSheetByName(tabName);
  if (!sheet) sheet = ss.getSheetByName('Read Me');
  if (!sheet) sheet = ss.getSheetByName('User Guide');

  if (sheet) {
    sheet.clear();
    sheet.clearConditionalFormatRules();
  } else {
    sheet = ss.insertSheet(tabName, 0);
  }

  const rows = [];
  
  // Row 1: Title Banner
  rows.push(['📖 FLEET DISPATCH EFFICIENCY ENGINE — METRIC DICTIONARY & GUIDE', '', '', '']);
  // Row 2: Subtitle
  rows.push(['A clear reference guide to understand and interpret all KPI cards, overhead ratios, and driver performance metrics.', '', '', '']);
  // Row 3: Spacer
  rows.push(['', '', '', '']);

  // Section 1: Top KPI Cards
  rows.push(['1. TOP KPI CARDS (Monthly & Master Summary Sheets)', '', '', '']);
  rows.push(['Metric Name', 'Calculation Logic', 'Business Definition & How to Read It', 'Example & Context']);
  
  const kpiData = [
    [
      'Total Fleet Driver Hours',
      'Sum of all driver active hours in the period',
      'Total cumulative hours all drivers spent on the road providing service during the month.',
      '909.0 hrs'
    ],
    [
      'Standard Dispatch Hours',
      'Timesheet WT / Base Calendar (Muhammad 10h Mon-Fri, Mariam 10h Mon-Wed,Fri,Sat, Nour 9h Mon-Fri)',
      'Total standard working hours deployed by the active dispatchers (Muhammad, Mariam, Nour). Excludes Mohanad & Abdulrahman.',
      '656.5 hrs (or calendar base)'
    ],
    [
      'Overtime / Adjustment (E4)',
      'Timesheet Overtime OT / Editable input cell',
      'Verified overtime hours from the Working Time timesheet or manual input. Modifying this cell updates all ratios live.',
      '61.0 hrs (or enter 0.0)'
    ],
    [
      'Total Dispatch Hours',
      'Standard Dispatch Hours + Overtime Hours',
      'The full pool of dispatch labor hours deployed during that month.',
      '717.5 hrs'
    ],
    [
      'Fleet Dispatch Ratio',
      'Total Dispatch Hours ÷ Total Fleet Driver Hours',
      'Dispatch Overhead Ratio: Represents how many hours of dispatch support are needed for every 1.0 hour of road driving. A lower ratio means higher labor efficiency.',
      '0.789 (0.79 dispatch hrs per 1 road hr)'
    ],
    [
      'Support Mins / Road Hr',
      'Fleet Dispatch Ratio × 60 minutes',
      'Human-Friendly Overhead: How many minutes of dispatcher support time are dedicated for every 1 hour a driver is driving on the road.',
      '47.3 mins per 1 road hr'
    ],
    [
      'Driver Leverage Ratio',
      'Total Fleet Driver Hours ÷ Total Dispatch Hours',
      'Labor Multiplier: The number of active road hours generated by the fleet for every 1 hour of dispatcher labor. Higher is better.',
      '1.27x (1.27 road hrs per 1 dispatch hr)'
    ]
  ];

  for (const row of kpiData) {
    rows.push(row);
  }

  rows.push(['', '', '', '']);

  // Section 2: Driver Comparison Table
  rows.push(['2. DRIVER COMPARISON TABLE (Individual Driver Metrics)', '', '', '']);
  rows.push(['Column Name', 'Calculation Logic', 'Business Definition & How to Read It', 'Strategic Interpretation']);

  const tableData = [
    [
      'Driver Name',
      'Aggregated from monthly records',
      'Unique driver name. All daily entries for this driver in the month are combined into this single row.',
      'Identifies individual driver performance.'
    ],
    [
      'Driver Active Hours',
      'Sum of driver\'s daily driving hours',
      'Total monthly driving hours logged on the road across all working days in that month.',
      'Evaluates driver workload and full-time vs part-time activity.'
    ],
    [
      '% Share of Fleet Hours',
      'Driver Active Hours ÷ Total Fleet Driver Hours',
      'The percentage of the total fleet road time contributed by this individual driver.',
      'Identifies top core contributors to overall operations.'
    ],
    [
      'Allocated Dispatch Hours',
      'Driver Active Hours × Fleet Dispatch Ratio',
      'The fair-share dispatch labor hours dedicated to supporting this driver based on their road time.',
      'Fair-share labor overhead attribution.'
    ],
    [
      'Completed Trips',
      'Sum of driver\'s daily trips',
      'Total successful passenger rides completed during the month.',
      'Direct volume output measurement.'
    ],
    [
      'Trips / Driver Hour',
      'Completed Trips ÷ Driver Active Hours',
      'Driver Productivity Pace: Average trips completed per driving hour on the road.',
      'Identifies high trip turnover and routing efficiency.'
    ],
    [
      'Trips / Dispatch Hour',
      'Completed Trips ÷ Allocated Dispatch Hours',
      'Dispatch Yield: Number of completed trips delivered per 1 hour of allocated dispatch labor.',
      'Measures overall operational throughput and dispatch ROI.'
    ]
  ];

  for (const row of tableData) {
    rows.push(row);
  }

  sheet.getRange(1, 1, rows.length, 4).setNumberFormat('@');
  sheet.getRange(1, 1, rows.length, 4).setValues(rows);

  formatReadMeSheet(sheet);

  return sheet;
}

function formatReadMeSheet(sheet) {
  sheet.getRange('A1:D1').merge()
    .setBackground('#1e293b')
    .setFontColor('#ffffff')
    .setFontSize(13)
    .setFontWeight('bold')
    .setVerticalAlignment('middle');
  sheet.setRowHeight(1, 40);

  sheet.getRange('A2:D2').merge()
    .setBackground('#334155')
    .setFontColor('#cbd5e1')
    .setFontSize(9)
    .setFontStyle('italic')
    .setVerticalAlignment('middle');
  sheet.setRowHeight(2, 22);

  sheet.getRange('A4:D4').merge()
    .setBackground('#0f172a')
    .setFontColor('#ffffff')
    .setFontWeight('bold')
    .setFontSize(10);
  sheet.setRowHeight(4, 26);

  sheet.getRange('A5:D5')
    .setBackground('#475569')
    .setFontColor('#ffffff')
    .setFontWeight('bold')
    .setFontSize(9)
    .setHorizontalAlignment('center');
  sheet.setRowHeight(5, 24);

  const kpiRange = sheet.getRange('A6:D12');
  kpiRange.setFontSize(9).setVerticalAlignment('middle');
  kpiRange.setBorder(true, true, true, true, true, true, '#cbd5e1', SpreadsheetApp.BorderStyle.SOLID);
  sheet.getRange('A6:A12').setFontWeight('bold').setBackground('#f8fafc');

  sheet.getRange('A14:D14').merge()
    .setBackground('#0f172a')
    .setFontColor('#ffffff')
    .setFontWeight('bold')
    .setFontSize(10);
  sheet.setRowHeight(14, 26);

  sheet.getRange('A15:D15')
    .setBackground('#475569')
    .setFontColor('#ffffff')
    .setFontWeight('bold')
    .setFontSize(9)
    .setHorizontalAlignment('center');
  sheet.setRowHeight(15, 24);

  const tableRange = sheet.getRange('A16:D22');
  tableRange.setFontSize(9).setVerticalAlignment('middle');
  tableRange.setBorder(true, true, true, true, true, true, '#cbd5e1', SpreadsheetApp.BorderStyle.SOLID);
  sheet.getRange('A16:A22').setFontWeight('bold').setBackground('#f8fafc');

  sheet.setColumnWidth(1, 220);
  sheet.setColumnWidth(2, 280);
  sheet.setColumnWidth(3, 440);
  sheet.setColumnWidth(4, 260);

  sheet.getRange('A1:D25').setWrap(true);
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    buildReadMeSheet,
    formatReadMeSheet
  };
}
